language: R
sudo: false
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

# Settings to mimic CRAN build
# Modified from github.com/jeroen/jsonlite
osx_image: xcode9

addons:
  apt:
    sources:
      # PPA for clang 6.0
      - llvm-toolchain-trusty-6.0
      # PPA for clang-format 8
      - llvm-toolchain-trusty
      # PPA for a more recen libstdc++
      - ubuntu-toolchain-r-test
    packages:
      - clang-format

r_packages:
  - Rcpp
  - RcppArmadillo
  - ggplot2
  - glmnet
  - ncvreg
  - covr

before_install:
  - bash script/format_check.sh || travis_terminate 1;
  - Rscript -e "source('build_steps.R'); before_install()"

after_success:
  - Rscript -e "source('build_steps.R'); after_success(); unlink('build_steps.R')"

branches:
  except:
    - build # Don't build "build" branch or else we get in an infinite loop

r_build_args: --no-manual --no-resave-data
r_check_args: --no-manual

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: .
  target_branch: build
  condition: $TRAVIS_OS_NAME = "linux"
